version: '3.9'

volumes:
  pgdata-dev:


services:
  sleep-bot-db-dev:
    container_name: sleep-bot-db-dev
    image: postgres:14-alpine
    restart: always
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
      PGDATA: /var/lib/postgresql/data/pgdata/
    ports:
      - "55432:5432"
